init:
 - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#  QTDIR: 'C:\Qt\5.9.1\msvc2015_64'
#  BOOST_ROOT: 'C:\Libraries\boost_1_59_0'
#  BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_59_0\lib64-msvc-14.0'
  #VCINSTALLDIR: 'c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\'
environment:
  LIMA_DIST: c:\d
  LIMA_CONF: 'c:\d\share\config\lima'
  LIMA_RESOURCES: 'c:\d\share\apps\lima\resources'
  QTDIR: 'C:\Qt\5.8\msvc2015_64'
  BOOST_ROOT: 'C:\Libraries\boost_1_63_0'
  BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_63_0\lib64-msvc-14.0'
  PATH: '%QTDIR%\bin;c:\d\bin;c:\d\share\apps\lima\scripts;%BOOST_LIBRARYDIR%;c:\msys64\usr\bin;%PATH%'
  LIMA_DISABLE_FSW_TESTING: true
  NLTK_PTB_DP_DIR: 'c:\dependency_treebank'
  NLTK_PTB_DP_FILE: 'c:\dependency_treebank\nltk-ptb.dp'
  BINTRAYKEY:
    secure: SF9KK/1ShDAudlHJFsZro1MQOaYqjJ0Hb2mbJEvFyxPCLHtevjyxuLT1IrsSmE1o

  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

configuration: Release

os: Visual Studio 2015
#os: Visual Studio 2013

install:
  # Prepend chosen Python to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  ############################################################################
  # All external dependencies are installed in C:\externals
  ############################################################################
  - mkdir C:\externals
  - cd C:\externals

  ############################################################################
  # Install Ninja
  ############################################################################
  - appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip
  - 7z x ninja.zip -oC:\externals\ninja > nul
  - set PATH=C:\externals\ninja;%PATH%
  - ninja --version

  - ps: (new-object net.webclient).DownloadFile('http://www.nltk.org/nltk_data/packages/corpora/dependency_treebank.zip', 'c:\dependency_treebank.zip')
  - ps: mkdir c:\dependency_treebank
  - ps: unzip c:\dependency_treebank.zip -d c:\
  - ps: cd c:\
  - c:\msys64\usr\bin\cat /c/dependency_treebank/wsj_*.dp | c:\msys64\usr\bin\grep -v "^$" > c:\dependency_treebank\nltk-ptb.dp

build_script:
  - mkdir c:\b
  - cd c:\b
  - echo %BOOST_ROOT%
  - echo %BOOST_LIBRARYDIR%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cmake -G "Ninja" "-DCMAKE_PREFIX_PATH=%QTDIR%;%BOOST_ROOT%" "-DLIMA_RESOURCES=build" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=c:\d" "-DBOOST_ROOT:STRING=%BOOST_ROOT%" "-DBOOST_LIBRARYDIR:STRING=%BOOST_LIBRARYDIR%" -DCMAKE_IGNORE_PATH="C:/msys64/usr/bin" c:/projects/lima
  - cmake --build . --config Release

on_success:
  - ps: ls c:/d/share/apps/lima/tests
  - ps: pushd c:/d/share/apps/lima/tests
  - ps: ( tva --language=eng test-eng.tokenizer.xml test-eng.simpleword.xml test-eng.idiom.xml test-eng.abbrev.xml test-eng.hyphen.xml test-eng.default.xml test-eng.se-PERSON.xml test-eng.se-DATE.xml test-eng.se-EMBEDED.xml test-eng.se-ORGANISATION.xml test-eng.se.xml test-eng.se-LOCATION.xml test-eng.disambiguated.xml test-eng.sa.xml 2>&1 | tee tva-eng.log ) -or $true
  - ps: ( tva --language=fre test-fre.tokenizer.xml test-fre.simpleword.xml test-fre.hyphen.xml test-fre.idiom.xml test-fre.default.xml test-fre.se.xml test-fre.disambiguated.xml test-fre.sa.xml 2>&1 | tee tva-fre.log ) -or $true
  - ps: popd

  #- ps: $user = "kleag"
  #- ps: $pass = $Env:BINTRAYKEY
  #- ps: $pair = "${user}:${pass}"
  #- ps: $bytes = [System.Text.Encoding]::ASCII.GetBytes($pair)
  #- ps: $base64 = [System.Convert]::ToBase64String($bytes)
  #- ps: $basicAuthValue = "Basic $base64"
  #- ps: $headers = @{ Authorization = $basicAuthValue }
  #- ps: $commit = $Env:APPVEYOR_REPO_COMMIT
  #- ps: $commit  = $commit.substring(0,7)
  #- ps: Invoke-RestMethod  -Method PUT -Headers $headers -uri https://api.bintray.com/content/kleag/windows64/lima/$Env:APPVEYOR_BUILD_NUMBER/$Env:APPVEYOR_BUILD_NUMBER/limacommon-2.1.$commit.exe?publish=1 -Infile C:/b/lima_common/src/lima_common-build/limacommon-2.1..exe
  #- ps: Invoke-RestMethod  -Method PUT -Headers $headers -uri https://api.bintray.com/content/kleag/windows64/lima/$Env:APPVEYOR_BUILD_NUMBER/$Env:APPVEYOR_BUILD_NUMBER/limalinguisticprocessing-2.1.$commit.exe?publish=1 -Infile C:/b/lima_linguisticprocessing/src/lima_linguisticprocessing-build/limalinguisticprocessing-2.1..exe
  #- ps: Invoke-RestMethod  -Method PUT -Headers $headers -uri https://api.bintray.com/content/kleag/windows64/lima/$Env:APPVEYOR_BUILD_NUMBER/$Env:APPVEYOR_BUILD_NUMBER/limalinguisticdata-2.1.$commit.exe?publish=1 -Infile C:/b/lima_linguisticdata/src/lima_linguisticdata-build/limalinguisticdata-2.1..exe
  #- ps: Invoke-RestMethod  -Method PUT -Headers $headers -uri https://api.bintray.com/content/kleag/windows64/lima/$Env:APPVEYOR_BUILD_NUMBER/$Env:APPVEYOR_BUILD_NUMBER/limagui-2.1.$commit.exe?publish=1 -Infile C:/b/lima_gui/src/lima_gui-build/limagui-2.1..exe


on_failure:
         - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))