language: cpp

addons:
  apt:
    sources:
    - ubuntu-sdk-team
    packages:
    - qtbase5-dev
    - qt5-default
    - qt5-qmake
    - qtcore5-dev
    - qttools5-dev-tools
    - qtbase5-dev-tools
    - libqt5svg5-dev
    - qttools5-dev
    - qtscript5-dev
    - qtdeclarative5-folderlistmodel-plugin
    - qtdeclarative5-controls-plugin
    - qtbase5-dev-tools
    - qtchooser
    - qtdeclarative5-dev

matrix:
  allow_failures:
    - os: osx
  # include:
  #   - os: linux
  #     compiler: clang
  #     sudo: required
  #   - os: linux
  #     compiler: gcc
  #     sudo: required
  #   - os: osx
  #     compiler: gcc
  #   - os: osx
  #     compiler: clang
  include:
    - os: linux
      env: QT_BASE=55 COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Debug
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9

    - os: linux
      env: QT_BASE=55 COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9

    - os: linux
      env: QT_BASE=55 COMPILER=g++-7 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-7
          - g++-7

before_script:
  - cmake --version
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; brew install qt5; brew link qt5 --force; fi

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - make -j8