# Ported from: https://github.com/aurora-fw/ci/
#
# Copyright (C) 2017 Aurora Framework, All rights reserved.
# Copyright (C) 2018 Enthusiastic Development, All rights reserved

branches:
  only:
    - master
    - dev
    - wip
    - linux
    - darwin
    - windows

language: cpp

matrix:
  allow_failures:
    - os: osx

  include:
    - os: linux
      compiler: clang
      sudo: required
      services: docker
    - os: linux
      compiler: gcc
      sudo: required
      services: docker
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang

arch:
  packages:
    - cmake
    - qt5-tools
    - qt5-base
    - qt5-declarative

  script:
    - cmake .
    - make -j8

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash;
    fi;

notifications:
  email:
    recipients: enthdevelopment@gmail.com
    on_success: always
    on_failure: always
  slack:
    rooms:
      secure: D"Y4ovYGtEzGJnlk5znWYIPCkW0B/+IJ18UCoORMR0mUsRRc8G3QhgsIdMjAnREUUIPuUpwPhSfdRfHUTVK2ws6EvdRc51izKCwObtTcszywWiPU/xNXtvw2pV7cTLESdVsGWrNuDW4XaIdaJG4LQrTKuWgL8UQWOZuAcofjyCFjXSmuCBNIDo2EytjcBKFRy7O2cte7blvqUQrIvWtALiha84huV7nzuQGQleu3hOLaMs2WluERTg43P98TwQ5JLoSVhIrEsHGbOxSUjq22jOBf3rxmItOnNemKi260VgYSD8oLVv6qgu16cBQQSM3uXhzhhUt2+ujigGT4QEYCQN/ArtB1+RIkIqzU/a7D+UFfYT5Yb97blD5Bb6oM4NIv1AH4wm73VrxyFfbVYD1C2loCjC/dT0vpqBtUxj3xarZyz+x/nSt/5fgVXs9EHHB7t7iqbHsqylTPa6BNYsD+zjXlT9WHzQTPggfA92XjhT+thCcKZRmFthSgGXrSYNsY+np14cDK0a/m+OVu1CRxaqhhbkyDpi4jUfI+GoAz7VMSYXXqAjE9nx6G8r+dKIbW2FKUmLT6GmmADwPUbh95vkKjfcnfKL71cJ4vw9nOBCrqnic8WY9ZBlBm34RoZhpoLTaHir0sbXOwpJ1DlqduirR8RdXvrN+r4tTy6MjR0VjI=
    on_success: always
    on_failure: always
