# Ported from: https://github.com/aurora-fw/ci/
#
# Copyright (C) 2017 Aurora Framework, All rights reserved.
# Copyright (C) 2018 Enthusiastic Development, All rights reserved

branches:
  only:
    - master
    - dev
    - wip
    - linux
    - darwin
    - windows

language: cpp

matrix:
  allow_failures:
    - os: osx

  include:
    - os: linux
      compiler: clang
      sudo: required
      services: docker
    - os: linux
      compiler: gcc
      sudo: required
      services: docker
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang

arch:
  packages:
    - cmake
    - qt5-tools
    - qt5-base
    - qt5-declarative

  script:
    - cmake .
    - make

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash;
    fi;